### ISSUE TITLE
Take pen names into account

### ISSUE THREAD

**Issue by islemaster** [JakeC007/hugo_stats#1]
In your summary results, you mention:

> The three authors with the most nominations are
>
>  1.  Seanan McGuire (7)
>  2.  Mira Grant (6)
>  3.  Aliette de Bodard (5)

However, [according to Wikipedia](https://en.m.wikipedia.org/wiki/Seanan_McGuire) "Mira Grant" is a pen name for Seanan McGuire. That feels like important context for interpreting these results. At the least, please add a note to this effect.

It would be interesting to see these results with pen names attributed back to the actual author, where possible - and probably makes the pattern of a large number of nominations going to a small number of authors even more acute.

**Comment by JakeC007** [comment]
Thanks so much for the heads up! I'll make an edit to the README and blog post accordingly. How do you want to be attributed?

**Comment by islemaster** [comment]
Thanks! The GitHub issue history is sufficient attribution for me.
